bookstoredjango/urls.py
from django.contrib import admin
from django.urls import path
from shop.views import *


urlpatterns = [
    path('', IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('shop', BookListView.as_view()),
    path('product-detail/<int:pk>', BookDetailView.as_view()),
    path('update_cart', updateCart),
    path('cart', show_cart),
    path('checkout', show_checkout),
    path('checkout-order', checkout_order, name='process')
]

shop/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Author(models.Model):
    name = models.CharField('author name', max_length=15)
    dob = models.DateField('author\'s date of birth')

    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField('title', max_length=15)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    img = models.ImageField('book photo')
    price = models.PositiveSmallIntegerField('price')

    def __str__(self):
        return self.title

    def get_details(self):
        return 'product-detail/' + str(self.id)


class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField('name', max_length=50)
    email = models.EmailField('email')


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    recepientName = models.CharField(max_length=60, null=True, default="")
    complete = models.BooleanField('complete', default=False)
    number = models.CharField(max_length=12, null=True, default=None)
    address = models.CharField(max_length=80, null=True, default=None)
    zipCode = models.CharField(max_length=8, null=True, default=None)
    comment = models.TextField(null=True, default=None)





class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField('quantity', default=0)

shop/views.py
import json

from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views import View

from .models import *
# Create your views here.


class BookListView(ListView):
    paginate_by = 6

    def get_queryset(self):
        return Book.objects.all()

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        count = 0
        if self.request.user.is_authenticated:
            order = Order.objects.get(customer=self.request.user.customer, complete=False)
            for _ in OrderItem.objects.filter(order=order):
                count += _.quantity
        context['order_count'] = count
        return context

    template_name = 'shop.html'

class BookDetailView(DetailView):
    model = Book
    slug_field = 'id'
    template_name = 'product-details.html'

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        count = 0
        if self.request.user.is_authenticated:
            order = Order.objects.get_or_create(customer=self.request.user.customer, complete=False)[0]
            for _ in OrderItem.objects.filter(order=order):
                count += _.quantity
        context['order_count'] = count
        return context

class IndexView(View):
    books = Book.objects.order_by('-id')[:9]
    def get(self, request):
        count = 0
        if self.request.user.is_authenticated:
            order = Order.objects.get_or_create(customer=request.user.customer, complete=False)[0]
            for _ in OrderItem.objects.filter(order=order):
                count += _.quantity
        return render(request, 'index.html', {'books': self.books, 'order_count': count})

def updateCart(request):
    data = json.loads(request.body)
    book_id = data['product_id']
    method = data['method']
    if 'qty' in data:
        qty = data['qty']
    else:
        qty = 1
    books = Book.objects.get(id=book_id)
    order = Order.objects.get_or_create(customer=request.user.customer, complete=False)[0]
    orderItem = OrderItem.objects.get_or_create(order=order, book=books)[0]
    if method == 'add':
        orderItem.quantity += qty
    elif method == 'remove':
        orderItem.quantity -= 1
    orderItem.save()
    if orderItem.quantity <= 0:
        orderItem.delete()

    return JsonResponse('OK', safe=False)


def get_cart(request):
    context = {}
    if request.user.is_authenticated:
        order = Order.objects.get_or_create(customer=request.user.customer, complete=False)[0]
        orderItems = OrderItem.objects.filter(order=order)
        count = 0
        total = 0
        for _ in orderItems:
            count += _.quantity
            total += _.quantity * _.book.price
        context = {
            'order': order,
            'orderItems': orderItems,
            'order_count': count,
            'total': total
        }
    return context


def show_cart(request):
    cart_details = get_cart(request)
    return render(request, 'cart.html',
                  cart_details)

def show_checkout(request):
    context = {}
    if request.user.is_authenticated:
        order = get_cart(request)['order']
        total = get_cart(request)['total']
        qty = get_cart(request)['order_count']
        context = {
            'order': order,
            'total': total,
            'order_count': qty
        }
    return render(request, 'checkout.html', context)

def checkout_order(request):
    data = request.POST
    order = Order.objects.get(customer=request.user.customer, complete=False)
    order.recepientName = data['name'] + ' ' + data['lastname']
    order.number = data['number']
    order.address = data['address']
    order.zipCode = data['zipcode']
    order.comment = data['comment']
    order.complete = True
    order.save()
    return redirect('/')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
{% include 'blocks/head.html' %}
<body>
<div class="main-content-wrapper d-flex clearfix">
{% include 'blocks/body.html' %}
    {% block content %}
    {% endblock content %}
</div>
{% include 'blocks/footer.html' %}
</body>
</html>

templates/blocks/body.html
{% load static %}
<div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        <form action="#" method="get">
                            <input type="search" name="search" id="search" placeholder="Type your keyword...">
                            <button type="submit"><img src="{% static 'img/core-img/search.png' %}" alt=""></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>



        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="index.html"><img src="img/core-img/logo.png" alt=""></a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo">
                <a href="index.html"><img src="img/core-img/logo.png" alt=""></a>
            </div>
            <!-- Amado Nav -->
            <nav class="amado-nav">
                <ul>
                    <li class="{% if request.path == '/' %}active{% endif %}"><a href="/">Home</a></li>
                    <li class="{% if request.path == '/shop' %}active{% endif %}"><a href="/shop">Shop</a></li>
                    <li class="{% if request.path == '/cart' %}active{% endif %}"><a href="/cart">Cart</a></li>
                    <li class="{% if request.path == '/checkout' %}active{% endif %}"><a href="/checkout">Checkout</a></li>
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="amado-btn-group mt-30 mb-100">
                <a href="#" class="btn amado-btn mb-15">%Discount%</a>
                <a href="#" class="btn amado-btn active">New this week</a>
            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a href="/cart" class="cart-nav"><img src="img/core-img/cart.png" alt=""> Cart <span id="cart">{{ order_count|default_if_none:0 }}</span></a>
                <a href="#" class="fav-nav"><img src="img/core-img/favorites.png" alt=""> Favourite</a>
                <a href="#" class="search-nav"><img src="img/core-img/search.png" alt=""> Search</a>
            </div>
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>

        </header>
        <!-- Header Area End -->

templates/blocks/footer.html
{% load static %}
 <!-- ##### Newsletter Area Start ##### -->
    <section class="newsletter-area section-padding-100-0">
        <div class="container">
            <div class="row align-items-center">
                <!-- Newsletter Text -->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="newsletter-text mb-100">
                        <h2>Subscribe for a <span>25% Discount</span></h2>
                        <p>Nulla ac convallis lorem, eget euismod nisl. Donec in libero sit amet mi vulputate consectetur. Donec auctor interdum purus, ac finibus massa bibendum nec.</p>
                    </div>
                </div>
                <!-- Newsletter Form -->
                <div class="col-12 col-lg-6 col-xl-5">
                    <div class="newsletter-form mb-100">
                        <form action="#" method="post">
                            <input type="email" name="email" class="nl-email" placeholder="Your E-mail">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Newsletter Area End ##### -->

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <a href="index.html"><img src="../static/img/core-img/logo2.png" alt=""></a>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <a class="nav-link" href="index.html">Home</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="shop.html">Shop</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="product-details.html">Product</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="cart.html">Cart</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link" href="checkout.html">Checkout</a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->

    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="../static/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="../static/js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="../static/js/bootstrap.min.js"></script>
    <!-- Plugins js -->
    <script src="../static/js/plugins.js"></script>
    <!-- Active js -->
    <script src="../static/js/active.js"></script>

templates/blocks/head.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title  -->
    <title>Amado</title>
    <!-- Favicon  -->
    <link rel="icon" href="{%  static 'img/core-img/favicon.ico' %}">
    <!-- Core Style CSS -->
    <link rel="stylesheet" href="{% static 'css/core-style.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
    <script>
        var user = "{{ request.user }}"
        console.log(user)
    </script>


</head>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <div class="cart-table-area section-padding-100">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 col-lg-8">
                        <div class="cart-title mt-50">
                            <h2>Shopping Cart</h2>
                        </div>

                        <div class="cart-table clearfix">
                            <table class="table table-responsive">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Name</th>
                                        <th>Price</th>
                                        <th>Quantity</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% for item in orderItems %}
                                    <tr>
                                        <td class="cart_product_img">
                                            <a href="{{ item.book.get_details }}"><img src="../static/img/bg-img/cart1.jpg" alt="Product"></a>
                                        </td>
                                        <td class="cart_product_desc">
                                            <h5>{{ item.book.title }}</h5>
                                        </td>
                                        <td class="price">
                                            <span>${{ item.book.price }}</span>
                                        </td>
                                        <td class="qty">
                                            <div class="qty-btn d-flex">
                                                <p>Qty</p>
                                                <div class="quantity">
                                                    <span data-id="{{ item.book_id }}" class="qty-minus"><i class="fa fa-minus" aria-hidden="true"></i> </span>
                                                    <input type="number" class="qty-text" id="qty" step="1" min="1" max="300" name="quantity" value="{{ item.quantity }}" disabled>
                                                    <span data-id="{{ item.book_id }}" class="qty-plus"><i class="fa fa-plus" aria-hidden="true"></i> </span>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div class="col-12 col-lg-4">
                        <div class="cart-summary">
                            <h5>Cart Total</h5>
                            <ul class="summary-table">
                                <li><span>total:</span> <span>${{ total }}</span></li>
                            </ul>
                            <div class="cart-btn mt-100">
                                <a href="checkout" class="btn amado-btn w-100">Checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- ##### Main Content Wrapper End ##### -->
    <script>
    const csrftoken = Cookies.get('csrftoken')
    var elem_minus = document.getElementsByClassName('qty-minus')
    var elem_plus = document.getElementsByClassName('qty-plus')
    for (var i = 0; i < elem_minus.length; i++){
        elem_minus[i].addEventListener('click', function (){
            var book = this.dataset.id
            UpdateCart(book, 'remove')
        })
    }
    for (var i = 0; i < elem_plus.length; i++){
        elem_plus[i].addEventListener('click', function (){
            var book = this.dataset.id
            UpdateCart(book, 'add')
        })
    }
    function UpdateCart(prod_id, method){
        var url = 'update_cart'
        fetch(url, {
            method:"POST",
            headers:{
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken
            },
        body:JSON.stringify({
                'product_id': prod_id,
                'method': method
        })
        })
        .then((response) => {
            console.log(response.status)
            return response.json()
        })
        .then((data) => {
            location.reload()
        })
        var cart = document.getElementById('cart')
        if (method == 'add'){
            cart.innerText = parseInt(document.getElementById('cart').innerText) + parseInt(1)
        }
        else if (method == 'remove'){
            cart.innerText = parseInt(document.getElementById('cart').innerText) - parseInt(1)
        }
        if (parseInt(cart.innerText) <= 0){
                cart.innerText = parseInt(0)
            }
    }
    </script>
{% endblock content %}

templates/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <div class="cart-table-area section-padding-100">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 col-lg-8">
                        <div class="checkout_details_area mt-50 clearfix">

                            <div class="cart-title">
                                <h2>Checkout</h2>
                            </div>
                            <form id="order_form" action="{% url 'process' %}" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-6 mb-3">
                                        <input type="text" name="name" class="form-control req" id="first_name" value="" placeholder="First Name" required>
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <input type="text" name="lastname" class="form-control req" id="last_name" value="" placeholder="Last Name" required>
                                    </div>
                                    <div class="col-12 mb-3">
                                        <input type="email" name="email" class="form-control req" id="email" placeholder="{{ request.user.customer.email }}" value="{{ request.user.customer.email }}">
                                    </div>
                                    <div class="col-12 mb-3">
                                        <input type="text" name="address" class="form-control mb-3 req" id="street_address" placeholder="Address" value="">
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <input type="text" name="zipcode" class="form-control req" id="zipCode" placeholder="Zip Code" value="">
                                    </div>
                                    <div class="col-md-6 mb-3">
                                        <input type="text" name="number" class="form-control req" id="phone_number" placeholder="Phone No" value="">
                                    </div>
                                    <div class="col-12 mb-3">
                                        <textarea name="comment" class="form-control w-100" id="comment" cols="30" rows="10" placeholder="Leave a comment about your order"></textarea>
                                    </div>
                                     <input id='sbm' type="submit" hidden="true">
                                </div>
                            </form>
                        </div>
                    </div>
                    <div class="col-12 col-lg-4">
                        <div class="cart-summary">
                            <h5>Cart Total</h5>
                            <ul class="summary-table">
                                <li><span>total:</span> <span>${{ total }}</span></li>
                            </ul>
                            <div class="cart-btn mt-100">
                                <a id="submit" href="#" class="btn amado-btn w-100">Checkout</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    <script>
    var req = document.getElementsByClassName('req')
    var submit_btn = document.getElementById('sbm')
    var send_btn = document.getElementById('submit')

    function validate_form(){
        for (var i = 0; i< req.length; i++){
            if (req[i].value == ""){
                return 0
            }
        }
        return 1
    }


    send_btn.addEventListener('click', function (){
        if (validate_form()){
            swal("Thank You!", "Your order is confirmed!", "success")
            setTimeout(function(){
                submit_btn.click()
            }, 1500)
        }
        else{
            swal("Oops!", "Not fields are filled!", "warning")
        }

    })
    </script>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!-- Product Catagories Area Start -->
        <div class="products-catagories-area clearfix">
            <div class="amado-pro-catagory clearfix">

                {% for book in books %}
                <!-- Single Catagory -->
                <div class="single-products-catagory clearfix">
                    <a href="/shop">
                        <img src="{% static 'img/bg-img/1.jpg' %}" alt="">
                        <!-- Hover Content -->
                        <div class="hover-content">
                            <div class="line"></div>
                            <p>{{ book.price }}</p>
                            <h4>{{ book.title }}</h4>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
{% endblock content %}

templates/shop.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <div class="shop_sidebar_area">
            <!-- ##### Single Widget ##### -->
            <div class="widget catagory mb-50">
                <!-- Widget Title -->
                <h6 class="widget-title mb-30">Catagories</h6>

                <!--  Catagories  -->
                <div class="catagories-menu">
                    <ul>
                        <li class="active"><a href="#">Chairs</a></li>
                        <li><a href="#">Beds</a></li>
                        <li><a href="#">Accesories</a></li>
                        <li><a href="#">Furniture</a></li>
                        <li><a href="#">Home Deco</a></li>
                        <li><a href="#">Dressings</a></li>
                        <li><a href="#">Tables</a></li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="amado_product_area section-padding-100">
            <div class="container-fluid">
                <div class="row">

                    {% for book in book_list %}
                    <!-- Single Product Area -->
                    <div class="col-12 col-sm-6 col-md-12 col-xl-6">
                        <div class="single-product-wrapper">
                            <!-- Product Image -->
                            <div class="product-img">
                                <img src="{% static 'img/product-img/product1.jpg' %}" alt="">
                                <!-- Hover Thumb -->
                                <img class="hover-img" src="{% static 'img/product-img/product2.jpg' %}" alt="">
                            </div>

                            <!-- Product Description -->
                            <div class="product-description d-flex align-items-center justify-content-between">
                                <!-- Product Meta Data -->
                                <div class="product-meta-data">
                                    <div class="line"></div>
                                    <p class="product-price">{{ book.price }}</p>
                                    <a href="{{ book.get_details }}">
                                        <h6>{{ book.title }}</h6>
                                    </a>
                                </div>
                                <!-- Ratings & Cart -->
                                <div class="ratings-cart text-right">
                                    <div class="ratings">
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                        <i class="fa fa-star" aria-hidden="true"></i>
                                    </div>
                                    <div class="cart">
                                        <a class="add-to-cart" data-id="{{ book.id }}" href="#" data-toggle="tooltip" data-placement="left" title="Add to Cart"><img src="{% static 'img/core-img/cart.png' %}" alt=""></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                <div class="row">
                    <div class="col-12">
                        <!-- Pagination -->
                        <nav aria-label="navigation">
                            <ul class="pagination justify-content-end mt-50">
                                {% if page_obj.has_previous %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number}}">{{ page_obj.previous_page_number}}</a></li>
                                {% endif %}

                                <li class="page-item active"><a class="page-link">{{ page_obj.number }}</a></li>

                                {% if page_obj.has_next %}
                                <li class="page-item"><a class="page-link" href="?page={{page_obj.next_page_number}}">{{ page_obj.next_page_number }}</a></li>
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
                </div>
            </div>
        </div>
    <script>
    const csrftoken = Cookies.get('csrftoken');
    var elems = document.getElementsByClassName('add-to-cart')
    for(var i = 0; i < elems.length; i++){
        elems[i].addEventListener('click', function (){
            var prod_id = this.dataset.id
            UpdateOrInsert(prod_id, 'add')
        })
    }
    function UpdateOrInsert(prod_id, method){
        var url = 'update_cart'
        fetch(url, {
            method:"POST",
            headers:{
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken
            },
        body:JSON.stringify({
                'product_id': prod_id,
                'method': method
        })
        })
        .then((response) => {
            console.log(response.status)
            return response.json()
        })
        .then((data) => {
            console.log(data)
            location.reload()
        })
        document.getElementById('cart').innerText = parseInt(1) + parseInt(document.getElementById('cart').innerText)
    }
    </script>
{% endblock content %}